### ISSUE TITLE
无法启动。java.lang.ClassNotFoundException: fuck_the_regulations_320.pb1

### ISSUE THREAD

**Issue by zoyaforever** [pengzhile/ja-netfilter#22]
通过idea.bat启动，报如下错误：

系统找不到指定的文件。

  ============================================================================

    ja-netfilter-v1.1.5

    A javaagent lib for network filter :)

    https://github.com/pengzhile/ja-netfilter

  ============================================================================

Exception in thread "main" java.lang.ExceptionInInitializerError
        at fuck_the_regulations_320.e9.<clinit>(e9.java:15)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.util.ConcurrentModificationException: java.lang.ClassNotFoundException: fuck_the_regulations_320.pb1
        at fuck_the_regulations_320.aZ.<clinit>(aZ.java:82)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: fuck_the_regulations_320.pb1
        at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:229)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at fuck_the_regulations_320.aZ.<clinit>(aZ.java:127)
        ... 7 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

**Comment by pengzhile** [comment]
去掉jetbrains-agent.jar的配置
